[WIP] Handle API authentication errors for the API services
astarte-platform/astarte pull request #1034
Opened 2024-12-11 14:44 UTC by arahmarchak

* [x] I have read [CONTRIBUTING.md](../CONTRIBUTING.md) and [CODE_OF_CONDUCT.md](../CODE_OF_CONDUCT.md)
* [ ] I have added to [CHANGELOG.md](../CHANGELOG.md) relevant changes and any other user facing change
* [x] I have added or ran the appropriate tests

#### What this PR does / why we need it:

- Expand the ```fallback_controller``` with some failed auth functions
- Add additional error views with useful feedback messages
- Add the ```gen_jwt_token_with_wrong_signature``` function in the ```JWTTestHelper```
- Add the necessary auth tests and adapt existing ones

#### Which issue(s) this PR fixes:

Fixes: #1031 

#### Special notes for your reviewer:
- Please note that the useful error message for the ```invalid_token_signature``` error is still not displayed.
- This PR currently contains 1 commit related to the RM API. I would like to get some initial feedback on the current state of the code.
- If everything looks good, I will add the remaining 3 quite similar commits but related to ```AppEngine```, ```Pairing``` and ```Housekeeping``` APIs.

##### Does this PR introduce a user-facing change?
* [ ] Yes
* [x] No

#### Additional documentation e.g. usage docs, diagrams, etc.: 
None

2025-01-10 13:21 UTC, Annopaolo commented on apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/error_view.ex
> +          "Authorization failed due to an invalid path. Ensure the realm name and endpoint are correctly specified in the request"
Nit: the path does not contain an Astarte endpoint, since this is Realm Management API. See https://docs.astarte-platform.org/astarte/latest/api/?urls.primaryName=Realm%20Management%20API for more

2025-01-13 13:46 UTC, eddbbt requested changes

2025-01-14 17:45 UTC, Annopaolo requested changes
I only looked superficially at the code and it looks good, I'd suggest adding the new errors to the OpenAPI schema of every app (`apps/$APP_NAME/priv/static/$APP_NAME.yaml`)

2025-01-15 12:38 UTC, arahmarchak commented
> I only looked superficially at the code and it looks good, I'd suggest adding the new errors to the OpenAPI schema of every app (`apps/$APP_NAME/priv/static/$APP_NAME.yaml`)

Since I'm going to change the .yaml files, should I change the contact email as well?
Current email: ```info@ispirata.com```

2025-01-16 11:30 UTC, eddbbt approved these changes
lgtm

2025-01-16 13:55 UTC, Annopaolo commented
> > I only looked superficially at the code and it looks good, I'd suggest adding the new errors to the OpenAPI schema of every app (`apps/$APP_NAME/priv/static/$APP_NAME.yaml`)
> 
> @Annopaolo Since I'm going to change the .yaml files, should I change the contact email as well? Current email: `info@ispirata.com`

Let's change it in another PR!

2025-01-16 13:55 UTC, Annopaolo approved these changes

2025-01-16 13:56 UTC, merged