Add Astarte Device SDKs page
astarte-platform/astarte pull request #468
Opened 2020-09-29 15:31 UTC by bettio

2020-09-29 15:44 UTC, rbino requested changes

2020-09-29 15:44 UTC, rbino commented on doc/pages/user/041-astarte_device_sdks.md
> +Virtually an SDK is not required to connect an application to Astarte using MQTT, but it enables
I'd remove "Virtually" here

2020-09-29 15:44 UTC, rbino commented on doc/pages/user/041-astarte_device_sdks.md
> +  * ESP32
Link to ESP32 SDK

2020-09-29 15:44 UTC, rbino commented on doc/pages/user/041-astarte_device_sdks.md
> +* C++
Are you using alphabetical order? If so, C++ must be moved up

2020-09-29 15:44 UTC, rbino requested changes

2020-09-29 15:44 UTC, rbino commented on doc/pages/user/041-astarte_device_sdks.md
> +Under the hood Astarte Device SDKs make use of MQTT, BSON, http, persistence and crypto libraries
I think that also HTTP should be uppercase

2022-03-25 16:17 UTC, bettio commented
This PR has been continued from @Annopaolo, let's close it.

2022-03-25 16:17 UTC, closed without merging