docs: Add needed steps to install cert-manager
astarte-platform/astarte pull request #508
Opened 2020-12-30 18:07 UTC by drf

cert-manager is a new needed dependency for Astarte Operator 1.0+ that has to be manually installed for a number of good reasons. Detail in the docs how to proceed and how to set up the Cluster.

2021-01-07 13:49 UTC, matt-mazzucato approved these changes

2021-01-08 14:57 UTC, rbino requested changes

2021-01-08 14:57 UTC, rbino commented on doc/pages/administrator/020-prerequisites.md
> +$ helm repo update
You have to manually create the `cert-manager` namespace here
```
kubectl create namespace cert-manager
 ```

2021-01-18 10:25 UTC, rbino approved these changes

2021-01-18 10:25 UTC, merged