Prepare 1.0.0-beta.1
astarte-platform/astarte pull request #532
Opened 2021-02-15 16:06 UTC by bettio

Bump version numbers.

2021-02-15 16:34 UTC, matt-mazzucato requested changes

2021-02-15 16:34 UTC, matt-mazzucato commented on doc/pages/administrator/030-installation_kubernetes.md
> -The most simple and common installation procedure exploits the [Astarte Operator's Helm
Something went wrong with the diff for this whole file. It is good as it is without applying the patch.

2021-02-15 17:24 UTC, matt-mazzucato approved these changes

2021-02-16 14:15 UTC, rbino approved these changes

2021-02-16 14:16 UTC, merged