E2e fix unknown failure
astarte-platform/astarte pull request #542
Opened 2021-02-24 17:18 UTC by matt-mazzucato

+ Update phoenix_gen_socket_client
+ Prevent failures from raising alerts with `unknown` id
+ Treat client disconnections as special cases which cause an immediate alert

2021-03-05 10:41 UTC, rbino requested changes
A rebase is needed

2021-03-05 10:41 UTC, rbino commented on tools/astarte_e2e/lib/astarte_e2e/service_notifier.ex
> +      |> Map.put(:failures_before_alert, data.failures_before_alert - 1)
Is this necessary? It starts from 0 so now it's going to `-1`

2021-03-08 11:38 UTC, bettio approved these changes

2021-03-08 11:40 UTC, rbino approved these changes

2021-03-08 11:41 UTC, merged