Add requirements for scylla db docker image
astarte-platform/astarte pull request #548
Opened 2021-03-09 16:19 UTC by Pavinati

Scylla requires /proc/sys/fs/aio-max-nr to be at least 1048576
See also https://github.com/scylladb/scylla/issues/5638

Signed-off-by: Mattia <mattia.pavinati@ispirata.com>

2021-03-09 16:26 UTC, rbino requested changes

2021-03-09 16:26 UTC, rbino commented on doc/pages/tutorials/010-astarte_in_5_minutes.md
> +If on working from a Linux machine, make sure your aio-max-nr is at least 1Mb
Make it:

Due to ScyllaDB requirements, if you're working on a Linux machine you should make sure that `aio-max-nr` is at least ` 1048576`: [...]

2021-03-09 16:26 UTC, rbino commented on doc/pages/tutorials/010-astarte_in_5_minutes.md
> +
Add the steps that have to be performed if it's _not_ the correct value, otherwise the user is left helpless here

2021-03-09 16:57 UTC, rbino requested changes

2021-03-09 16:57 UTC, rbino commented on doc/pages/tutorials/010-astarte_in_5_minutes.md
> +```sh
Blank line before code block

2021-03-09 16:57 UTC, rbino commented on doc/pages/tutorials/010-astarte_in_5_minutes.md
> +and to persist this configuration
Blank line after and before code block

2021-03-10 08:36 UTC, rbino approved these changes

2021-03-15 15:11 UTC, bettio approved these changes

2021-03-15 15:11 UTC, merged