Fix Cassandra warning in Realm Management logs
astarte-platform/astarte pull request #571
Opened 2021-04-16 15:58 UTC by Annopaolo

Remove `aggregation query without partition key` Cassandra warning when checking Astarte's health.
See #420.

2021-04-19 12:35 UTC, rbino requested changes

2021-04-19 12:35 UTC, rbino commented on apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
> +    query_schema = """
Let's keep the naming convention: this is a statement (so `schema_statement`), the query is the thing built from the statement + consistency + other stuff (so `schema_query`)

2021-04-19 12:35 UTC, rbino commented on apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
> +    query_realms = """
See above (this should be `realms_statement`)

2021-04-19 12:35 UTC, rbino commented on apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
> +    query_schema =
See above (this should be `schema_query`, the old version was actually wrong)

2021-04-19 12:35 UTC, rbino commented on apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
> +    query_realms =
`realms_query`

2021-04-19 12:35 UTC, rbino commented on apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
> +    query_realms = """
Also, add a comment to explain why that realm name was chosen so that we can remind our future selves the next time we end up here

2021-04-19 12:35 UTC, rbino commented on apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
> +    query_schema = """
See all the comments in the other implementation of the function

2021-04-19 12:35 UTC, rbino commented on apps/astarte_realm_management/lib/astarte_realm_management/queries.ex
> +          Logger.warn("Cannot retrieve heath query data.",
*health

2021-04-23 14:41 UTC, bettio approved these changes

2021-04-23 14:43 UTC, rbino approved these changes

2021-04-23 14:44 UTC, bettio requested changes
Missing changelog entry here.

2021-04-23 15:03 UTC, Annopaolo commented
> Missing changelog entry here.

@bettio done!

2021-04-23 15:17 UTC, bettio approved these changes

2021-04-23 15:46 UTC, merged