Update documentation
astarte-platform/astarte pull request #579
Opened 2021-05-03 15:48 UTC by matt-mazzucato

Document the procedure for handling the Operator deletion.

2021-05-05 14:19 UTC, bettio requested changes

2021-05-05 14:19 UTC, bettio commented on doc/pages/administrator/095-advanced-operations.md
> +### Backup your resources
Backup you resources should be moved to top level, it is more general than uninstall itself.

2021-05-05 14:19 UTC, bettio commented on doc/pages/administrator/095-advanced-operations.md
> +### Apply backed up resources
The same applies here.

2021-05-05 16:40 UTC, bettio approved these changes

2021-05-10 15:06 UTC, rbino commented on doc/pages/administrator/095-advanced-operations.md
> +Backing up your Astarte resources is crucial in all those cases in which your Astarte instance have
has

2021-05-10 15:07 UTC, rbino commented on doc/pages/administrator/095-advanced-operations.md
> +if** your Cassandra StatefulSet is deployed independently from Astarte, i.e. it must be deployed
call it "Cassandra/Scylla instance" instead of StatefulSet, since usually if it's external it is not even a StatefulSet

2021-05-10 15:11 UTC, rbino commented on doc/pages/administrator/095-advanced-operations.md
> +Even if removing the Operator potentially can destroy your Astarte instance, there is a way to
can potentially

2021-05-10 15:41 UTC, merged