AppEngine: do not crash on some malformed POST/PUT requests
astarte-platform/astarte pull request #706
Opened 2022-05-10 11:05 UTC by Annopaolo

Instead of failing, return a 403 Forbidden error if:
- A client tries to publish data on a device-owned interface;
- A client tries to publish data on an incomplete path of a server-owned interface.

Close #264 .

2022-05-10 11:13 UTC, Pavinati approved these changes

2022-06-08 16:08 UTC, rbino approved these changes

2022-06-08 16:12 UTC, rbino requested changes
As mentioned in the [linked issue](https://github.com/astarte-platform/astarte/issues/264) the code to be returned should probably be 405 (`put_status(:method_not_allowed`)), since 403 is more centered around auth/authz. The code was crashing before so we're free to change the return code anyway.

2022-06-09 08:44 UTC, Pavinati approved these changes

2022-06-09 09:51 UTC, bettio approved these changes

2022-06-09 09:51 UTC, merged