Doc: use new URLs in "Astarte in 5 minutes"
astarte-platform/astarte pull request #769
Opened 2023-03-30 16:19 UTC by Annopaolo

Use the addresses exposed by Traefik rather than clunky ports.

2023-03-30 16:19 UTC, Annopaolo commented
Based, based on #768 .

2023-03-30 16:33 UTC, Pavinati commented on doc/pages/tutorials/010-astarte_in_5_minutes.md
> +It will bring up a Traefik instance to expose Astarte services. You can reach Astarte at the following addresses:
I wouldn't mention Traefik here. People Reading this guide are focused on trying out Astarte without going too much into how it  works under the hood

2023-03-30 16:33 UTC, Pavinati commented on doc/pages/tutorials/010-astarte_in_5_minutes.md
> +* `api.localhost`: Astarte API
Maybe it's still worth mentioning the services URLs, expecially pairing, considering it's used by stream-test Qt5

2023-03-30 16:45 UTC, davidebriani commented on docker-compose.yml
> +    #   - "1885:1885"
We can remove this if unused

2023-03-30 16:46 UTC, davidebriani approved these changes

2023-05-09 16:03 UTC, Pavinati requested changes

2023-05-09 16:03 UTC, Pavinati commented on doc/pages/tutorials/010-astarte_in_5_minutes.md
> +Moreover, Astarte's Docker Compose also installs [Astarte Dashboard](https://github.com/astarte-platform/astarte-dashboard), from which you can manage your Realms and install Triggers, Interfaces and
`dashboard.astarte.localhost` instead of `http://dashboard.localhost`

2023-05-09 16:04 UTC, rbino approved these changes

2023-05-09 16:32 UTC, Pavinati approved these changes

2023-05-15 08:23 UTC, Annopaolo commented
Drafted until #780 is merged.

2023-05-19 09:06 UTC, merged