RM API: Return a correctly-formatted Trigger Delivery Policy
astarte-platform/astarte pull request #774
Opened 2023-04-07 13:59 UTC by arahmarchak

Display incorrect and excessive parameters solved by excluded keyword and error_codes from error_handlers field to get correctly-formatted Trigger Policy.

Modified policy view and updated key conversion to handle JSON decoding.

2023-04-11 13:16 UTC, Annopaolo requested changes

2023-04-11 13:16 UTC, Annopaolo commented on apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/trigger_policy_controller.ex
> +         {:ok, decoded_json} <- Jason.decode(policy_source, keys: :atoms!) do
Put a comment on why `keys: :atoms!` was added

2023-04-12 15:01 UTC, Annopaolo requested changes

2023-04-13 08:40 UTC, Annopaolo requested changes

2023-04-13 08:40 UTC, Annopaolo commented on apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/views/trigger_policy_view.ex
> +      |> Enum.map(&normalize_handler/1)
When there's only a single function, it's better not to use the pipe operator

2023-04-13 15:06 UTC, Annopaolo approved these changes

2023-04-17 09:38 UTC, rbino requested changes

2023-04-17 09:38 UTC, rbino commented on apps/astarte_realm_management_api/lib/astarte_realm_management_api_web/controllers/trigger_policy_controller.ex
> +         # Use (safe) atoms as keys to simplify handler normalization in Trigger Policy View
This is ok as a temporary workaround, but in the long run we should add a `from_source` function to `Astarte.Core.Trigger.Policy`. So please add another line with:
```
# TODO: move this to a function in Astarte Core building a Policy from its source
```
so we don't forget to do this in a following iteration

2023-05-03 13:05 UTC, rbino approved these changes

2023-05-03 13:09 UTC, merged