Init nix for development
astarte-platform/astarte pull request #787
Opened 2023-05-29 14:04 UTC by noaccOS

Init nix's development shell as an alternative to asdf. It can be used from both a standard nix-shell
or a nix develop with flakes.

MIX_HOME and HEX_HOME are set do directories in the project root to avoid conflicts with system packages.

.envrc is provided for use with direnv, defaulting to the flake version of the shell.

2023-06-12 14:46 UTC, bettio requested changes

2023-06-12 14:46 UTC, bettio commented on .nix/beam-overlay.nix
> +    version = "1.11.4";
1.14.5

2023-06-12 14:46 UTC, bettio commented on .nix/beam-overlay.nix
> +    version = "23.2.7";
25.3.2

2023-06-14 08:51 UTC, noaccOS commented on .nix/beam-overlay.nix
> +    version = "23.2.7";
dependencies should now be up to date

2023-06-14 16:26 UTC, Annopaolo approved these changes

2023-11-08 14:17 UTC, Annopaolo approved these changes

2023-11-08 14:18 UTC, merged