Move `explicit_timestamp` to mapping section.
astarte-platform/astarte pull request #846
Opened 2023-09-25 10:32 UTC by sorru94

Closes #844

2023-09-25 16:27 UTC, Annopaolo requested changes

2023-09-25 16:27 UTC, Annopaolo commented on doc/pages/architecture/040-interface_schema.md
> +### astarte.interface.schema.explicit_timestamp
```suggestion
### astarte.mapping.schema.explicit_timestamp
```

2023-09-27 13:17 UTC, Annopaolo approved these changes

2023-09-27 14:04 UTC, matt-mazzucato approved these changes

2023-09-28 08:43 UTC, merged