chore(doc): add the websocket url for channels
astarte-platform/astarte pull request #987
Opened 2024-08-27 14:52 UTC by joshuachp

Specify in the Astarte Channels documentation page the AppEngine URL for the WebSocket channel.

2024-08-27 15:25 UTC, joshuachp commented
I've updated the documentation groups in the API reference, under the advice of @davidebriani to also include the WebSocket Channels.

2024-08-27 16:01 UTC, davidebriani approved these changes

2024-08-27 16:13 UTC, eddbbt approved these changes

2024-09-02 14:56 UTC, Annopaolo requested changes
Looks good! Would you mind rebasing on `release-1.1`?

2024-09-03 08:41 UTC, joshuachp commented
Rebased on the release

2024-09-03 08:56 UTC, Annopaolo approved these changes

2024-09-03 08:56 UTC, merged